site_name: My Docs
site_name: 'LLM: RAG Applications'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: custom
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: custom


plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          #docstring_section_style: list
          #modernize_annotations: true
          parameter_headings: true
          merge_init_into_class: true
          show_source: false
          show_labels: true
          show_signature_annotations: true
          show_root_heading: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          show_category_heading: true

  

markdown_extensions:
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list

repo_url: https://github.com/Miciox5/ICOS/tree/develop
repo_name: Miciox5/ICOS

nav:
  - Home:
    - index.md
  - Get started:
    - get-started/installation.md
    - get-started/quickstart.md
  - API reference:
    - reference/ICOS/callbacks.md
    - reference/ICOS/chain.md
    - reference/ICOS/chroma.md
    - reference/ICOS/chunker.md
    - reference/ICOS/client.md
    - reference/ICOS/constants.md
    - reference/ICOS/converter.md
    - reference/ICOS/embedding.md
    - reference/ICOS/history.md
    - reference/ICOS/ingest.md
    - reference/ICOS/loader.md
    - reference/ICOS/memory.md
    - reference/ICOS/model.md
    - reference/ICOS/mongo.md
    - reference/ICOS/preprocessing.md
    - reference/ICOS/prompt_template.md
    - reference/ICOS/server-langserve.md
    - reference/ICOS/session.md
    - reference/ICOS/upload_files.md
    - reference/ICOS/uploader.md
    - reference/ICOS/utils.md
    - reference/ICOS/wikipedia.md