site_name: 'LLM: RAG Applications'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: custom
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: custom

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Miciox5/ICOS/tree/develop
    - icon: fontawesome/brands/docker
    - icon: fontawesome/brands/slack

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py 
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          #docstring_section_style: list
          separate_signature: false
          modernize_annotations: true
          heading_level: 2
          parameter_headings: true
          merge_init_into_class: true
          show_source: false
          show_labels: true
          show_signature_annotations: true
          show_root_heading: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          show_category_heading: true

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
 

repo_url: https://github.com/Miciox5/ICOS/tree/develop
repo_name: Miciox5/ICOS

nav:
  - Home:
    - index.md
  - Get started:
    - get-started/installation.md
    - get-started/quickstart.md
  - Guides:
    - guides/prompting.md
  - API reference:
    - Callbacks:
      - reference/ICOS/callbacks/handler.md
    - Chains:
      - reference/ICOS/chains/base.md
      - reference/ICOS/chains/self_query_constructor.md
    - LLMs:
      - Clients:
        - reference/ICOS/llms/clients/openllm.md
    - Loaders:
      - reference/ICOS/loaders/callbacks.md
      - reference/ICOS/loaders/documents.md
      - reference/ICOS/loaders/embedding.md
      - reference/ICOS/loaders/local.md
      - reference/ICOS/loaders/model.md
      - reference/ICOS/loaders/remote.md
    - Runnables:
      - reference/ICOS/runnables/history.md
    - Server:
      - reference/ICOS/server/langserve.md
      - reference/ICOS/server/session.md
    - Text Splitters:
      - reference/ICOS/text_splitters/chunker.md
    - Utils:
      - reference/ICOS/utils/converter.md
      - reference/ICOS/utils/uploader.md
      - reference/ICOS/utils/wikipedia.md
    - Vector Stores:
      - reference/ICOS/vector_stores/chroma.md